[2018-05-29 12:08:45 +0200] [12792] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:08:45 +0200] [12792] [INFO] Listening at: http://0.0.0.0:7755 (12792)
[2018-05-29 12:08:45 +0200] [12792] [INFO] Using worker: sync
[2018-05-29 12:08:45 +0200] [12795] [INFO] Booting worker with pid: 12795
[2018-05-29 12:08:45 +0200] [12795] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named 'app'
[2018-05-29 12:08:45 +0200] [12795] [INFO] Worker exiting (pid: 12795)
[2018-05-29 12:08:45 +0200] [12792] [INFO] Shutting down: Master
[2018-05-29 12:08:45 +0200] [12792] [INFO] Reason: Worker failed to boot.
[2018-05-29 12:08:59 +0200] [12796] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:08:59 +0200] [12796] [INFO] Listening at: http://0.0.0.0:7755 (12796)
[2018-05-29 12:08:59 +0200] [12796] [INFO] Using worker: sync
[2018-05-29 12:08:59 +0200] [12799] [INFO] Booting worker with pid: 12799
[2018-05-29 12:08:59 +0200] [12799] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named 'app'
[2018-05-29 12:08:59 +0200] [12799] [INFO] Worker exiting (pid: 12799)
[2018-05-29 12:08:59 +0200] [12796] [INFO] Shutting down: Master
[2018-05-29 12:08:59 +0200] [12796] [INFO] Reason: Worker failed to boot.
[2018-05-29 12:09:03 +0200] [12800] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:09:03 +0200] [12800] [INFO] Listening at: http://0.0.0.0:7755 (12800)
[2018-05-29 12:09:03 +0200] [12800] [INFO] Using worker: sync
[2018-05-29 12:09:03 +0200] [12803] [INFO] Booting worker with pid: 12803
[2018-05-29 12:09:03 +0200] [12803] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named 'asdfasdfapp'
[2018-05-29 12:09:03 +0200] [12803] [INFO] Worker exiting (pid: 12803)
[2018-05-29 12:09:03 +0200] [12800] [INFO] Shutting down: Master
[2018-05-29 12:09:03 +0200] [12800] [INFO] Reason: Worker failed to boot.
[2018-05-29 12:09:30 +0200] [12807] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:09:30 +0200] [12807] [INFO] Listening at: http://0.0.0.0:7755 (12807)
[2018-05-29 12:09:30 +0200] [12807] [INFO] Using worker: sync
[2018-05-29 12:09:30 +0200] [12810] [INFO] Booting worker with pid: 12810
[2018-05-29 12:09:36 +0200] [12807] [INFO] Handling signal: int
[2018-05-29 12:09:36 +0200] [12810] [INFO] Worker exiting (pid: 12810)
[2018-05-29 12:09:36 +0200] [12807] [INFO] Shutting down: Master
[2018-05-29 12:14:44 +0200] [12866] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:14:44 +0200] [12866] [INFO] Listening at: http://0.0.0.0:7777 (12866)
[2018-05-29 12:14:44 +0200] [12866] [INFO] Using worker: sync
[2018-05-29 12:14:44 +0200] [12870] [INFO] Booting worker with pid: 12870
[2018-05-29 12:14:54 +0200] [12870] [INFO] Worker exiting (pid: 12870)
[2018-05-29 12:14:54 +0200] [12866] [INFO] Handling signal: term
[2018-05-29 12:14:54 +0200] [12866] [INFO] Shutting down: Master
[2018-05-29 12:43:13 +0200] [13191] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:43:13 +0200] [13191] [INFO] Listening at: http://0.0.0.0:7777 (13191)
[2018-05-29 12:43:13 +0200] [13191] [INFO] Using worker: sync
[2018-05-29 12:43:13 +0200] [13195] [INFO] Booting worker with pid: 13195
[2018-05-29 12:44:52,014] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 46, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-29 12:48:10 +0200] [13191] [INFO] Handling signal: term
[2018-05-29 12:48:10 +0200] [13195] [INFO] Worker exiting (pid: 13195)
[2018-05-29 12:48:10 +0200] [13191] [INFO] Shutting down: Master
[2018-05-29 12:49:42 +0200] [13328] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:49:42 +0200] [13328] [INFO] Listening at: http://0.0.0.0:7777 (13328)
[2018-05-29 12:49:42 +0200] [13328] [INFO] Using worker: sync
[2018-05-29 12:49:42 +0200] [13332] [INFO] Booting worker with pid: 13332
[2018-05-29 12:49:50,898] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 46, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-29 12:50:08 +0200] [13328] [INFO] Handling signal: term
[2018-05-29 12:50:08 +0200] [13332] [INFO] Worker exiting (pid: 13332)
[2018-05-29 12:50:08 +0200] [13328] [INFO] Shutting down: Master
[2018-05-29 12:50:18 +0200] [13368] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:50:18 +0200] [13368] [INFO] Listening at: http://0.0.0.0:7755 (13368)
[2018-05-29 12:50:18 +0200] [13368] [INFO] Using worker: sync
[2018-05-29 12:50:18 +0200] [13371] [INFO] Booting worker with pid: 13371
[2018-05-29 12:50:27 +0200] [13368] [INFO] Handling signal: int
[2018-05-29 12:50:27 +0200] [13371] [INFO] Worker exiting (pid: 13371)
[2018-05-29 12:50:27 +0200] [13368] [INFO] Shutting down: Master
[2018-05-29 12:50:32 +0200] [13374] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:50:32 +0200] [13374] [INFO] Listening at: http://0.0.0.0:7777 (13374)
[2018-05-29 12:50:32 +0200] [13374] [INFO] Using worker: sync
[2018-05-29 12:50:32 +0200] [13377] [INFO] Booting worker with pid: 13377
[2018-05-29 12:51:01 +0200] [13374] [INFO] Handling signal: int
[2018-05-29 12:51:01 +0200] [13377] [INFO] Worker exiting (pid: 13377)
[2018-05-29 12:51:02 +0200] [13374] [INFO] Shutting down: Master
[2018-05-29 12:54:05 +0200] [13385] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:54:05 +0200] [13385] [INFO] Listening at: http://0.0.0.0:7777 (13385)
[2018-05-29 12:54:05 +0200] [13385] [INFO] Using worker: sync
[2018-05-29 12:54:05 +0200] [13388] [INFO] Booting worker with pid: 13388
[2018-05-29 12:54:14,947] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 46, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-29 12:55:54,205] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 46, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-29 12:55:57 +0200] [13385] [INFO] Handling signal: int
[2018-05-29 12:55:57 +0200] [13388] [INFO] Worker exiting (pid: 13388)
[2018-05-29 12:55:58 +0200] [13385] [INFO] Shutting down: Master
[2018-05-29 12:56:01 +0200] [13392] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:56:01 +0200] [13392] [INFO] Listening at: http://0.0.0.0:7777 (13392)
[2018-05-29 12:56:01 +0200] [13392] [INFO] Using worker: sync
[2018-05-29 12:56:01 +0200] [13395] [INFO] Booting worker with pid: 13395
[2018-05-29 12:56:07 +0200] [13392] [INFO] Handling signal: winch
[2018-05-29 12:56:13,874] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 46, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-29 12:57:33 +0200] [13392] [INFO] Handling signal: winch
[2018-05-29 12:57:34 +0200] [13392] [INFO] Handling signal: int
[2018-05-29 12:57:34 +0200] [13395] [INFO] Worker exiting (pid: 13395)
[2018-05-29 12:57:34 +0200] [13392] [INFO] Shutting down: Master
[2018-05-29 12:58:58 +0200] [13400] [INFO] Starting gunicorn 19.8.1
[2018-05-29 12:58:58 +0200] [13400] [INFO] Listening at: http://0.0.0.0:7777 (13400)
[2018-05-29 12:58:58 +0200] [13400] [INFO] Using worker: sync
[2018-05-29 12:58:58 +0200] [13403] [INFO] Booting worker with pid: 13403
[2018-05-29 12:59:01 +0200] [13400] [INFO] Handling signal: winch
[2018-05-29 12:59:13 +0200] [13400] [INFO] Handling signal: winch
[2018-05-29 12:59:15 +0200] [13400] [INFO] Handling signal: int
[2018-05-29 12:59:15 +0200] [13403] [INFO] Worker exiting (pid: 13403)
[2018-05-29 12:59:16 +0200] [13400] [INFO] Shutting down: Master
[2018-05-29 13:05:52 +0000] [2115] [INFO] Starting gunicorn 19.4.5
[2018-05-29 13:05:52 +0000] [2115] [INFO] Listening at: http://0.0.0.0:7777 (2115)
[2018-05-29 13:05:52 +0000] [2115] [INFO] Using worker: sync
[2018-05-29 13:05:52 +0000] [2119] [INFO] Booting worker with pid: 2119
[2018-05-29 13:05:52 +0000] [2119] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 366, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 25
SyntaxError: Non-ASCII character '\xc3' in file /home/listas/consulta_fondo/app.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 366, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 25
SyntaxError: Non-ASCII character '\xc3' in file /home/listas/consulta_fondo/app.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
[2018-05-29 13:05:52 +0000] [2119] [INFO] Worker exiting (pid: 2119)
[2018-05-29 13:05:52 +0000] [2115] [INFO] Shutting down: Master
[2018-05-29 13:05:52 +0000] [2115] [INFO] Reason: Worker failed to boot.
[2018-05-29 13:06:20 +0000] [2152] [INFO] Starting gunicorn 19.4.5
[2018-05-29 13:06:20 +0000] [2152] [INFO] Listening at: http://0.0.0.0:7777 (2152)
[2018-05-29 13:06:20 +0000] [2152] [INFO] Using worker: sync
[2018-05-29 13:06:20 +0000] [2156] [INFO] Booting worker with pid: 2156
[2018-05-29 13:06:20 +0000] [2156] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 366, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 25
SyntaxError: Non-ASCII character '\xc3' in file /home/listas/consulta_fondo/app.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 366, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 25
SyntaxError: Non-ASCII character '\xc3' in file /home/listas/consulta_fondo/app.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
[2018-05-29 13:06:20 +0000] [2156] [INFO] Worker exiting (pid: 2156)
[2018-05-29 13:06:20 +0000] [2152] [INFO] Shutting down: Master
[2018-05-29 13:06:20 +0000] [2152] [INFO] Reason: Worker failed to boot.
[2018-05-29 13:07:00 +0200] [2159] [INFO] Starting gunicorn 19.8.1
[2018-05-29 13:07:00 +0200] [2159] [INFO] Listening at: http://0.0.0.0:7777 (2159)
[2018-05-29 13:07:00 +0200] [2159] [INFO] Using worker: sync
[2018-05-29 13:07:00 +0200] [2162] [INFO] Booting worker with pid: 2162
[2018-05-29 13:07:30 +0200] [2159] [INFO] Handling signal: int
[2018-05-29 13:07:30 +0200] [2162] [INFO] Worker exiting (pid: 2162)
[2018-05-29 13:07:30 +0200] [2159] [INFO] Shutting down: Master
[2018-05-29 13:09:15 +0200] [2199] [INFO] Starting gunicorn 19.8.1
[2018-05-29 13:09:15 +0200] [2199] [INFO] Listening at: http://0.0.0.0:7777 (2199)
[2018-05-29 13:09:15 +0200] [2199] [INFO] Using worker: sync
[2018-05-29 13:09:15 +0200] [2202] [INFO] Booting worker with pid: 2202
[2018-05-29 13:09:27 +0200] [2199] [INFO] Handling signal: int
[2018-05-29 13:09:27 +0200] [2202] [INFO] Worker exiting (pid: 2202)
[2018-05-29 13:09:27 +0200] [2199] [INFO] Shutting down: Master
[2018-05-29 13:15:25 +0200] [2383] [INFO] Starting gunicorn 19.8.1
[2018-05-29 13:15:25 +0200] [2383] [INFO] Listening at: http://0.0.0.0:7777 (2383)
[2018-05-29 13:15:25 +0200] [2383] [INFO] Using worker: sync
[2018-05-29 13:15:25 +0200] [2389] [INFO] Booting worker with pid: 2389
[2018-05-30 12:10:37 +0200] [2389] [INFO] Worker exiting (pid: 2389)
[2018-05-30 12:10:37 +0200] [2383] [INFO] Handling signal: term
[2018-05-30 12:10:37 +0200] [2383] [INFO] Shutting down: Master
[2018-05-30 12:10:40 +0200] [6020] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:10:40 +0200] [6020] [INFO] Listening at: http://0.0.0.0:7777 (6020)
[2018-05-30 12:10:40 +0200] [6020] [INFO] Using worker: sync
[2018-05-30 12:10:40 +0200] [6024] [INFO] Booting worker with pid: 6024
[2018-05-30 12:10:47,478] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 47, in formulario
    item = re.sub("[⁰-9]", "", item)
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 575, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range ⁰-9 at position 1
[2018-05-30 12:11:09 +0200] [6020] [INFO] Handling signal: term
[2018-05-30 12:11:09 +0200] [6024] [INFO] Worker exiting (pid: 6024)
[2018-05-30 12:11:09 +0200] [6020] [INFO] Shutting down: Master
[2018-05-30 12:16:48 +0200] [6463] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:16:48 +0200] [6463] [INFO] Listening at: http://0.0.0.0:7777 (6463)
[2018-05-30 12:16:48 +0200] [6463] [INFO] Using worker: sync
[2018-05-30 12:16:48 +0200] [6466] [INFO] Booting worker with pid: 6466
[2018-05-30 12:17:03,815] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 47, in formulario
    item = re.sub("[⁰-9]", "", item)
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 575, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range ⁰-9 at position 1
[2018-05-30 12:17:08 +0200] [6463] [INFO] Handling signal: int
[2018-05-30 12:17:08 +0200] [6466] [INFO] Worker exiting (pid: 6466)
[2018-05-30 12:17:08 +0200] [6463] [INFO] Shutting down: Master
[2018-05-30 12:19:48 +0200] [6474] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:19:48 +0200] [6474] [INFO] Listening at: http://0.0.0.0:7777 (6474)
[2018-05-30 12:19:48 +0200] [6474] [INFO] Using worker: sync
[2018-05-30 12:19:48 +0200] [6477] [INFO] Booting worker with pid: 6477
[2018-05-30 12:21:45 +0200] [6474] [INFO] Handling signal: int
[2018-05-30 12:21:45 +0200] [6477] [INFO] Worker exiting (pid: 6477)
[2018-05-30 12:21:45 +0200] [6474] [INFO] Shutting down: Master
[2018-05-30 12:22:38 +0200] [6482] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:22:38 +0200] [6482] [INFO] Listening at: http://0.0.0.0:7777 (6482)
[2018-05-30 12:22:38 +0200] [6482] [INFO] Using worker: sync
[2018-05-30 12:22:38 +0200] [6485] [INFO] Booting worker with pid: 6485
[2018-05-30 12:22:43,567] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 49, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/series.py", line 3587, in isin
    result = algorithms.isin(self, values)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/algorithms.py", line 405, in isin
    .format(values_type=type(values).__name__))
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [str]
[2018-05-30 12:22:48 +0200] [6482] [INFO] Handling signal: int
[2018-05-30 12:22:48 +0200] [6485] [INFO] Worker exiting (pid: 6485)
[2018-05-30 12:22:48 +0200] [6482] [INFO] Shutting down: Master
[2018-05-30 12:23:07 +0200] [6489] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:23:07 +0200] [6489] [INFO] Listening at: http://0.0.0.0:7777 (6489)
[2018-05-30 12:23:07 +0200] [6489] [INFO] Using worker: sync
[2018-05-30 12:23:07 +0200] [6492] [INFO] Booting worker with pid: 6492
[2018-05-30 12:23:16 +0200] [6489] [INFO] Handling signal: int
[2018-05-30 12:23:16 +0200] [6492] [INFO] Worker exiting (pid: 6492)
[2018-05-30 12:23:16 +0200] [6489] [INFO] Shutting down: Master
[2018-05-30 12:23:30 +0200] [6496] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:23:30 +0200] [6496] [INFO] Listening at: http://0.0.0.0:7777 (6496)
[2018-05-30 12:23:30 +0200] [6496] [INFO] Using worker: sync
[2018-05-30 12:23:30 +0200] [6499] [INFO] Booting worker with pid: 6499
[2018-05-30 12:23:42 +0200] [6496] [INFO] Handling signal: int
[2018-05-30 12:23:42 +0200] [6499] [INFO] Worker exiting (pid: 6499)
[2018-05-30 12:23:42 +0200] [6496] [INFO] Shutting down: Master
[2018-05-30 12:24:10 +0200] [6536] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:24:10 +0200] [6536] [INFO] Listening at: http://0.0.0.0:7777 (6536)
[2018-05-30 12:24:10 +0200] [6536] [INFO] Using worker: sync
[2018-05-30 12:24:10 +0200] [6540] [INFO] Booting worker with pid: 6540
[2018-05-30 12:33:47 +0200] [6536] [INFO] Handling signal: term
[2018-05-30 12:33:47 +0200] [6540] [INFO] Worker exiting (pid: 6540)
[2018-05-30 12:33:47 +0200] [6536] [INFO] Shutting down: Master
[2018-05-30 12:33:52 +0200] [6614] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:33:52 +0200] [6614] [INFO] Listening at: http://0.0.0.0:7777 (6614)
[2018-05-30 12:33:52 +0200] [6614] [INFO] Using worker: sync
[2018-05-30 12:33:52 +0200] [6619] [INFO] Booting worker with pid: 6619
[2018-05-30 12:37:19 +0200] [6619] [INFO] Worker exiting (pid: 6619)
[2018-05-30 12:37:19 +0200] [6614] [INFO] Handling signal: term
[2018-05-30 12:37:19 +0200] [6614] [INFO] Shutting down: Master
[2018-05-30 12:37:21 +0200] [6690] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:37:21 +0200] [6690] [INFO] Listening at: http://0.0.0.0:7777 (6690)
[2018-05-30 12:37:21 +0200] [6690] [INFO] Using worker: sync
[2018-05-30 12:37:21 +0200] [6696] [INFO] Booting worker with pid: 6696
[2018-05-30 12:54:07 +0200] [6696] [INFO] Worker exiting (pid: 6696)
[2018-05-30 12:54:07 +0200] [6690] [INFO] Handling signal: term
[2018-05-30 12:54:07 +0200] [6690] [INFO] Shutting down: Master
[2018-05-30 12:54:14 +0200] [6771] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:54:14 +0200] [6771] [INFO] Listening at: http://0.0.0.0:7777 (6771)
[2018-05-30 12:54:14 +0200] [6771] [INFO] Using worker: sync
[2018-05-30 12:54:14 +0200] [6775] [INFO] Booting worker with pid: 6775
[2018-05-30 12:54:19,821] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 45, in formulario
    listaIsbnConsulta = re.findall(r'\d[—.\d-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d[—.-\/]?\s?\d', cadena)
  File "/usr/lib/python3.5/re.py", line 213, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 570, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range \d-\/ at position 5
[2018-05-30 12:55:48 +0200] [6775] [INFO] Worker exiting (pid: 6775)
[2018-05-30 12:55:48 +0200] [6771] [INFO] Handling signal: term
[2018-05-30 12:55:48 +0200] [6771] [INFO] Shutting down: Master
[2018-05-30 12:55:50 +0200] [6846] [INFO] Starting gunicorn 19.8.1
[2018-05-30 12:55:50 +0200] [6846] [INFO] Listening at: http://0.0.0.0:7777 (6846)
[2018-05-30 12:55:50 +0200] [6846] [INFO] Using worker: sync
[2018-05-30 12:55:50 +0200] [6850] [INFO] Booting worker with pid: 6850
[2018-05-30 13:56:32 +0200] [6846] [INFO] Handling signal: term
[2018-05-30 13:56:32 +0200] [6850] [INFO] Worker exiting (pid: 6850)
[2018-05-30 13:56:32 +0200] [6846] [INFO] Shutting down: Master
[2018-05-30 13:57:10 +0200] [6903] [INFO] Starting gunicorn 19.8.1
[2018-05-30 13:57:10 +0200] [6903] [INFO] Listening at: http://0.0.0.0:7777 (6903)
[2018-05-30 13:57:10 +0200] [6903] [INFO] Using worker: sync
[2018-05-30 13:57:10 +0200] [6906] [INFO] Booting worker with pid: 6906
[2018-05-30 13:57:14 +0200] [6903] [INFO] Handling signal: int
[2018-05-30 13:57:14 +0200] [6906] [INFO] Worker exiting (pid: 6906)
[2018-05-30 13:57:15 +0200] [6903] [INFO] Shutting down: Master
[2018-05-30 13:57:36 +0200] [6922] [INFO] Starting gunicorn 19.8.1
[2018-05-30 13:57:36 +0200] [6922] [INFO] Listening at: http://0.0.0.0:7777 (6922)
[2018-05-30 13:57:36 +0200] [6922] [INFO] Using worker: sync
[2018-05-30 13:57:36 +0200] [6925] [INFO] Booting worker with pid: 6925
[2018-05-30 13:58:03 +0200] [6922] [INFO] Handling signal: int
[2018-05-30 13:58:03 +0200] [6925] [INFO] Worker exiting (pid: 6925)
[2018-05-30 13:58:03 +0200] [6922] [INFO] Shutting down: Master
[2018-05-31 08:48:15 +0200] [8434] [INFO] Starting gunicorn 19.8.1
[2018-05-31 08:48:15 +0200] [8434] [INFO] Listening at: http://0.0.0.0:7777 (8434)
[2018-05-31 08:48:15 +0200] [8434] [INFO] Using worker: sync
[2018-05-31 08:48:15 +0200] [8437] [INFO] Booting worker with pid: 8437
[2018-05-31 08:48:20 +0200] [8434] [INFO] Handling signal: winch
[2018-05-31 08:49:17 +0200] [8434] [INFO] Handling signal: winch
[2018-05-31 08:49:31 +0200] [8434] [INFO] Handling signal: int
[2018-05-31 08:49:31 +0200] [8437] [INFO] Worker exiting (pid: 8437)
[2018-05-31 08:49:31 +0200] [8434] [INFO] Shutting down: Master
[2018-05-31 08:53:31 +0200] [8536] [INFO] Starting gunicorn 19.8.1
[2018-05-31 08:53:31 +0200] [8536] [INFO] Listening at: http://0.0.0.0:7777 (8536)
[2018-05-31 08:53:31 +0200] [8536] [INFO] Using worker: sync
[2018-05-31 08:53:31 +0200] [8539] [INFO] Booting worker with pid: 8539
[2018-05-31 08:53:34 +0200] [8536] [INFO] Handling signal: winch
[2018-05-31 08:53:47,689] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 47, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-31 08:53:52 +0200] [8536] [INFO] Handling signal: winch
[2018-05-31 08:53:56 +0200] [8536] [INFO] Handling signal: int
[2018-05-31 08:53:56 +0200] [8539] [INFO] Worker exiting (pid: 8539)
[2018-05-31 08:53:56 +0200] [8536] [INFO] Shutting down: Master
[2018-05-31 08:55:51 +0200] [8567] [INFO] Starting gunicorn 19.8.1
[2018-05-31 08:55:51 +0200] [8567] [INFO] Listening at: http://0.0.0.0:7777 (8567)
[2018-05-31 08:55:51 +0200] [8567] [INFO] Using worker: sync
[2018-05-31 08:55:51 +0200] [8570] [INFO] Booting worker with pid: 8570
[2018-05-31 08:56:08 +0200] [8567] [INFO] Handling signal: int
[2018-05-31 08:56:08 +0200] [8570] [INFO] Worker exiting (pid: 8570)
[2018-05-31 08:56:08 +0200] [8567] [INFO] Shutting down: Master
[2018-05-31 08:56:38 +0200] [8641] [INFO] Starting gunicorn 19.8.1
[2018-05-31 08:56:38 +0200] [8641] [INFO] Listening at: http://0.0.0.0:7777 (8641)
[2018-05-31 08:56:38 +0200] [8641] [INFO] Using worker: sync
[2018-05-31 08:56:38 +0200] [8646] [INFO] Booting worker with pid: 8646
[2018-05-31 08:56:50,515] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 47, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-31 08:57:00 +0200] [8641] [INFO] Handling signal: term
[2018-05-31 08:57:00 +0200] [8646] [INFO] Worker exiting (pid: 8646)
[2018-05-31 08:57:01 +0200] [8641] [INFO] Shutting down: Master
[2018-05-31 08:58:07 +0200] [8728] [INFO] Starting gunicorn 19.8.1
[2018-05-31 08:58:07 +0200] [8728] [INFO] Listening at: http://0.0.0.0:7777 (8728)
[2018-05-31 08:58:07 +0200] [8728] [INFO] Using worker: sync
[2018-05-31 08:58:07 +0200] [8733] [INFO] Booting worker with pid: 8733
[2018-05-31 08:58:30 +0200] [8728] [INFO] Handling signal: term
[2018-05-31 08:58:30 +0200] [8733] [INFO] Worker exiting (pid: 8733)
[2018-05-31 08:58:30 +0200] [8728] [INFO] Shutting down: Master
[2018-05-31 08:58:44 +0200] [8862] [INFO] Starting gunicorn 19.8.1
[2018-05-31 08:58:44 +0200] [8862] [INFO] Listening at: http://0.0.0.0:7777 (8862)
[2018-05-31 08:58:44 +0200] [8862] [INFO] Using worker: sync
[2018-05-31 08:58:44 +0200] [8866] [INFO] Booting worker with pid: 8866
[2018-05-31 08:59:07,904] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 47, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-31 08:59:33,360] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 47, in formulario
    fondo_filtrado = fondo[fondo.loc[:, 'ISBN'].isin(listaIsbnConsulta)]
NameError: name 'fondo' is not defined
[2018-05-31 09:04:17 +0200] [8982] [INFO] Starting gunicorn 19.8.1
[2018-05-31 09:04:17 +0200] [8982] [ERROR] Connection in use: ('0.0.0.0', 7777)
[2018-05-31 09:04:17 +0200] [8982] [ERROR] Retrying in 1 second.
[2018-05-31 09:04:18 +0200] [8982] [ERROR] Connection in use: ('0.0.0.0', 7777)
[2018-05-31 09:04:18 +0200] [8982] [ERROR] Retrying in 1 second.
[2018-05-31 09:04:19 +0200] [8982] [ERROR] Connection in use: ('0.0.0.0', 7777)
[2018-05-31 09:04:19 +0200] [8982] [ERROR] Retrying in 1 second.
[2018-05-31 09:04:20 +0200] [8982] [ERROR] Connection in use: ('0.0.0.0', 7777)
[2018-05-31 09:04:20 +0200] [8982] [ERROR] Retrying in 1 second.
[2018-05-31 09:04:21 +0200] [8982] [ERROR] Connection in use: ('0.0.0.0', 7777)
[2018-05-31 09:04:21 +0200] [8982] [ERROR] Retrying in 1 second.
[2018-05-31 09:04:22 +0200] [8982] [ERROR] Can't connect to ('0.0.0.0', 7777)
[2018-05-31 09:04:31,821] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 47, in formulario
NameError: name 'fondo' is not defined
[2018-05-31 09:05:13,545] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 47, in formulario
NameError: name 'fondo' is not defined
[2018-05-31 09:07:01 +0200] [8866] [INFO] Worker exiting (pid: 8866)
[2018-05-31 09:07:01 +0200] [8862] [INFO] Handling signal: term
[2018-05-31 09:07:01 +0200] [8862] [INFO] Shutting down: Master
[2018-05-31 09:08:45 +0200] [9237] [INFO] Starting gunicorn 19.8.1
[2018-05-31 09:08:45 +0200] [9237] [INFO] Listening at: http://0.0.0.0:7777 (9237)
[2018-05-31 09:08:45 +0200] [9237] [INFO] Using worker: sync
[2018-05-31 09:08:45 +0200] [9242] [INFO] Booting worker with pid: 9242
[2018-05-31 09:17:26 +0200] [9242] [INFO] Worker exiting (pid: 9242)
[2018-05-31 09:17:26 +0200] [9237] [INFO] Handling signal: term
[2018-05-31 09:17:26 +0200] [9237] [INFO] Shutting down: Master
[2018-05-31 09:18:12 +0200] [1211] [INFO] Starting gunicorn 19.8.1
[2018-05-31 09:18:12 +0200] [1211] [INFO] Listening at: http://0.0.0.0:7777 (1211)
[2018-05-31 09:18:12 +0200] [1211] [INFO] Using worker: sync
[2018-05-31 09:18:12 +0200] [1374] [INFO] Booting worker with pid: 1374
[2018-05-31 09:19:20 +0200] [1374] [INFO] Worker exiting (pid: 1374)
[2018-05-31 09:19:20 +0200] [1211] [INFO] Handling signal: term
[2018-05-31 09:19:20 +0200] [1211] [INFO] Shutting down: Master
[2018-05-31 10:38:04 +0200] [2466] [INFO] Starting gunicorn 19.8.1
[2018-05-31 10:38:04 +0200] [2466] [INFO] Listening at: http://0.0.0.0:7777 (2466)
[2018-05-31 10:38:04 +0200] [2466] [INFO] Using worker: sync
[2018-05-31 10:38:04 +0200] [2472] [INFO] Booting worker with pid: 2472
[2018-05-31 11:34:30 +0200] [2466] [INFO] Handling signal: term
[2018-05-31 11:34:30 +0200] [2472] [INFO] Worker exiting (pid: 2472)
[2018-05-31 11:34:30 +0200] [2466] [INFO] Shutting down: Master
[2018-05-31 11:34:30 +0200] [2613] [INFO] Starting gunicorn 19.8.1
[2018-05-31 11:34:30 +0200] [2613] [INFO] Listening at: http://0.0.0.0:7777 (2613)
[2018-05-31 11:34:30 +0200] [2613] [INFO] Using worker: sync
[2018-05-31 11:34:30 +0200] [2619] [INFO] Booting worker with pid: 2619
[2018-05-31 11:36:03 +0200] [2613] [INFO] Handling signal: term
[2018-05-31 11:36:03 +0200] [2619] [INFO] Worker exiting (pid: 2619)
[2018-05-31 11:36:03 +0200] [2613] [INFO] Shutting down: Master
[2018-05-31 11:36:03 +0200] [2663] [INFO] Starting gunicorn 19.8.1
[2018-05-31 11:36:03 +0200] [2663] [INFO] Listening at: http://0.0.0.0:7777 (2663)
[2018-05-31 11:36:03 +0200] [2663] [INFO] Using worker: sync
[2018-05-31 11:36:03 +0200] [2668] [INFO] Booting worker with pid: 2668
[2018-05-31 11:38:00 +0200] [2668] [INFO] Worker exiting (pid: 2668)
[2018-05-31 11:38:00 +0200] [2663] [INFO] Handling signal: term
[2018-05-31 11:38:00 +0200] [2663] [INFO] Shutting down: Master
[2018-05-31 11:38:00 +0200] [2679] [INFO] Starting gunicorn 19.8.1
[2018-05-31 11:38:00 +0200] [2679] [INFO] Listening at: http://0.0.0.0:7777 (2679)
[2018-05-31 11:38:00 +0200] [2679] [INFO] Using worker: sync
[2018-05-31 11:38:00 +0200] [2685] [INFO] Booting worker with pid: 2685
[2018-05-31 11:38:54 +0200] [2679] [INFO] Handling signal: term
[2018-05-31 11:38:54 +0200] [2685] [INFO] Worker exiting (pid: 2685)
[2018-05-31 11:38:54 +0200] [2679] [INFO] Shutting down: Master
[2018-05-31 11:38:54 +0200] [2696] [INFO] Starting gunicorn 19.8.1
[2018-05-31 11:38:54 +0200] [2696] [INFO] Listening at: http://0.0.0.0:7777 (2696)
[2018-05-31 11:38:54 +0200] [2696] [INFO] Using worker: sync
[2018-05-31 11:38:54 +0200] [2700] [INFO] Booting worker with pid: 2700
[2018-05-31 11:40:44 +0200] [2696] [INFO] Handling signal: term
[2018-05-31 11:40:44 +0200] [2700] [INFO] Worker exiting (pid: 2700)
[2018-05-31 11:40:44 +0200] [2696] [INFO] Shutting down: Master
[2018-05-31 11:40:44 +0200] [2711] [INFO] Starting gunicorn 19.8.1
[2018-05-31 11:40:44 +0200] [2711] [INFO] Listening at: http://0.0.0.0:7777 (2711)
[2018-05-31 11:40:44 +0200] [2711] [INFO] Using worker: sync
[2018-05-31 11:40:44 +0200] [2715] [INFO] Booting worker with pid: 2715
[2018-05-31 11:44:42 +0200] [2715] [INFO] Worker exiting (pid: 2715)
[2018-05-31 11:44:42 +0200] [2711] [INFO] Handling signal: term
[2018-05-31 11:44:42 +0200] [2711] [INFO] Shutting down: Master
[2018-05-31 11:44:42 +0200] [2791] [INFO] Starting gunicorn 19.8.1
[2018-05-31 11:44:42 +0200] [2791] [INFO] Listening at: http://0.0.0.0:7777 (2791)
[2018-05-31 11:44:42 +0200] [2791] [INFO] Using worker: sync
[2018-05-31 11:44:42 +0200] [2797] [INFO] Booting worker with pid: 2797
[2018-05-31 15:35:07 +0200] [2797] [INFO] Worker exiting (pid: 2797)
[2018-05-31 15:35:07 +0200] [2791] [INFO] Handling signal: term
[2018-05-31 15:35:07 +0200] [2791] [INFO] Shutting down: Master
[2018-05-31 15:35:07 +0200] [3030] [INFO] Starting gunicorn 19.8.1
[2018-05-31 15:35:07 +0200] [3030] [INFO] Listening at: http://0.0.0.0:7777 (3030)
[2018-05-31 15:35:07 +0200] [3030] [INFO] Using worker: sync
[2018-05-31 15:35:07 +0200] [3035] [INFO] Booting worker with pid: 3035
[2018-06-01 07:51:13 +0200] [3030] [CRITICAL] WORKER TIMEOUT (pid:3035)
[2018-06-01 07:51:14 +0200] [3704] [INFO] Booting worker with pid: 3704
[2018-06-01 07:57:09 +0200] [3030] [CRITICAL] WORKER TIMEOUT (pid:3704)
[2018-06-01 07:57:10 +0200] [3708] [INFO] Booting worker with pid: 3708
[2018-06-01 09:32:23 +0200] [3708] [INFO] Worker exiting (pid: 3708)
[2018-06-01 09:32:23 +0200] [3030] [INFO] Handling signal: term
[2018-06-01 09:32:23 +0200] [3030] [INFO] Shutting down: Master
[2018-06-01 09:32:23 +0200] [3783] [INFO] Starting gunicorn 19.8.1
[2018-06-01 09:32:23 +0200] [3783] [INFO] Listening at: http://0.0.0.0:7777 (3783)
[2018-06-01 09:32:23 +0200] [3783] [INFO] Using worker: sync
[2018-06-01 09:32:23 +0200] [3789] [INFO] Booting worker with pid: 3789
[2018-06-01 09:32:29,033] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 86, in formulario
    fondo_filtrado = fondo_filtrado.replace(np.nan, '-')
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/frame.py", line 3795, in replace
    method=method)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/generic.py", line 5879, in replace
    regex=regex)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/internals.py", line 3720, in replace
    return self.apply('replace', **kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/internals.py", line 3581, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/internals.py", line 2432, in replace
    if not either_list and is_re(to_replace):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/dtypes/inference.py", line 219, in is_re
    return isinstance(obj, re_type)
  File "/usr/lib/python3.5/typing.py", line 260, in __instancecheck__
    raise TypeError("Type aliases cannot be used with isinstance().")
TypeError: Type aliases cannot be used with isinstance().
[2018-06-01 09:32:57,625] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 86, in formulario
    fondo_filtrado = fondo_filtrado.replace(np.nan, '-')
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/frame.py", line 3795, in replace
    method=method)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/generic.py", line 5879, in replace
    regex=regex)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/internals.py", line 3720, in replace
    return self.apply('replace', **kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/internals.py", line 3581, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/internals.py", line 2432, in replace
    if not either_list and is_re(to_replace):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/core/dtypes/inference.py", line 219, in is_re
    return isinstance(obj, re_type)
  File "/usr/lib/python3.5/typing.py", line 260, in __instancecheck__
    raise TypeError("Type aliases cannot be used with isinstance().")
TypeError: Type aliases cannot be used with isinstance().
[2018-06-01 09:33:12 +0200] [3783] [INFO] Handling signal: term
[2018-06-01 09:33:12 +0200] [3789] [INFO] Worker exiting (pid: 3789)
[2018-06-01 09:33:13 +0200] [3783] [INFO] Shutting down: Master
[2018-06-01 09:36:57 +0200] [3898] [INFO] Starting gunicorn 19.8.1
[2018-06-01 09:36:57 +0200] [3898] [INFO] Listening at: http://0.0.0.0:7777 (3898)
[2018-06-01 09:36:57 +0200] [3898] [INFO] Using worker: sync
[2018-06-01 09:36:57 +0200] [3902] [INFO] Booting worker with pid: 3902
[2018-06-01 09:39:55 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:3902)
[2018-06-01 09:39:56 +0200] [3905] [INFO] Booting worker with pid: 3905
[2018-06-01 09:40:58 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:3905)
[2018-06-01 09:40:59 +0200] [3909] [INFO] Booting worker with pid: 3909
[2018-06-01 09:43:00 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:3909)
[2018-06-01 09:43:01 +0200] [3912] [INFO] Booting worker with pid: 3912
[2018-06-01 09:47:05 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:3912)
[2018-06-01 09:47:06 +0200] [3915] [INFO] Booting worker with pid: 3915
[2018-06-01 09:52:05 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:3915)
[2018-06-01 09:52:06 +0200] [4065] [INFO] Booting worker with pid: 4065
[2018-06-01 09:53:28 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:4065)
[2018-06-01 09:53:29 +0200] [4188] [INFO] Booting worker with pid: 4188
[2018-06-01 10:11:40 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:4188)
[2018-06-01 10:11:41 +0200] [4344] [INFO] Booting worker with pid: 4344
[2018-06-01 10:12:45 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:4344)
[2018-06-01 10:12:46 +0200] [4458] [INFO] Booting worker with pid: 4458
[2018-06-01 10:14:42 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:4458)
[2018-06-01 10:14:43 +0200] [4573] [INFO] Booting worker with pid: 4573
[2018-06-01 10:18:39 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:4573)
[2018-06-01 10:18:40 +0200] [4715] [INFO] Booting worker with pid: 4715
[2018-06-01 10:27:09 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:4715)
[2018-06-01 10:27:10 +0200] [4943] [INFO] Booting worker with pid: 4943
[2018-06-01 10:27:41 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:4943)
[2018-06-01 10:27:42 +0200] [4946] [INFO] Booting worker with pid: 4946
[2018-06-01 10:33:10 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:4946)
[2018-06-01 10:33:11 +0200] [5064] [INFO] Booting worker with pid: 5064
[2018-06-01 10:50:53 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:5064)
[2018-06-01 10:50:54 +0200] [5180] [INFO] Booting worker with pid: 5180
[2018-06-01 10:58:50 +0200] [3898] [CRITICAL] WORKER TIMEOUT (pid:5180)
[2018-06-01 10:58:51 +0200] [5186] [INFO] Booting worker with pid: 5186
[2018-06-01 11:53:07 +0200] [5186] [INFO] Worker exiting (pid: 5186)
[2018-06-01 11:53:07 +0200] [3898] [INFO] Handling signal: term
[2018-06-01 11:53:07 +0200] [3898] [INFO] Shutting down: Master
[2018-06-01 11:54:27 +0200] [5564] [INFO] Starting gunicorn 19.8.1
[2018-06-01 11:54:27 +0200] [5564] [INFO] Listening at: http://0.0.0.0:7777 (5564)
[2018-06-01 11:54:27 +0200] [5564] [INFO] Using worker: sync
[2018-06-01 11:54:27 +0200] [5568] [INFO] Booting worker with pid: 5568
[2018-06-01 12:04:44 +0200] [5568] [INFO] Worker exiting (pid: 5568)
[2018-06-01 12:04:44 +0200] [5564] [INFO] Handling signal: term
[2018-06-01 12:04:44 +0200] [5564] [INFO] Shutting down: Master
[2018-06-01 12:04:45 +0200] [5580] [INFO] Starting gunicorn 19.8.1
[2018-06-01 12:04:45 +0200] [5580] [INFO] Listening at: http://0.0.0.0:7777 (5580)
[2018-06-01 12:04:45 +0200] [5580] [INFO] Using worker: sync
[2018-06-01 12:04:45 +0200] [5586] [INFO] Booting worker with pid: 5586
[2018-06-01 12:31:12 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:5586)
[2018-06-01 12:31:13 +0200] [5596] [INFO] Booting worker with pid: 5596
[2018-06-01 13:05:09 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:5596)
[2018-06-01 13:05:10 +0200] [5604] [INFO] Booting worker with pid: 5604
[2018-06-01 13:06:30 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:5604)
[2018-06-01 13:06:31 +0200] [5607] [INFO] Booting worker with pid: 5607
[2018-06-01 13:17:40 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:5607)
[2018-06-01 13:17:41 +0200] [5613] [INFO] Booting worker with pid: 5613
[2018-06-01 13:57:43 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:5613)
[2018-06-01 13:57:44 +0200] [5620] [INFO] Booting worker with pid: 5620
[2018-06-01 13:58:23 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:5620)
[2018-06-01 13:58:24 +0200] [5623] [INFO] Booting worker with pid: 5623
[2018-06-01 13:59:06 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:5623)
[2018-06-01 13:59:07 +0200] [5626] [INFO] Booting worker with pid: 5626
[2018-06-04 10:51:35 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:5626)
[2018-06-04 10:51:37 +0200] [8652] [INFO] Booting worker with pid: 8652
[2018-06-04 10:56:59 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8652)
[2018-06-04 10:57:00 +0200] [8656] [INFO] Booting worker with pid: 8656
[2018-06-04 11:08:22 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8656)
[2018-06-04 11:08:23 +0200] [8660] [INFO] Booting worker with pid: 8660
[2018-06-04 11:54:04 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8660)
[2018-06-04 11:54:05 +0200] [8672] [INFO] Booting worker with pid: 8672
[2018-06-04 11:55:16 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8672)
[2018-06-04 11:55:17 +0200] [8675] [INFO] Booting worker with pid: 8675
[2018-06-04 11:56:13 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8675)
[2018-06-04 11:56:14 +0200] [8678] [INFO] Booting worker with pid: 8678
[2018-06-04 11:59:36 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8678)
[2018-06-04 11:59:37 +0200] [8682] [INFO] Booting worker with pid: 8682
[2018-06-04 12:08:51 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8682)
[2018-06-04 12:08:52 +0200] [8914] [INFO] Booting worker with pid: 8914
[2018-06-04 12:14:24 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8914)
[2018-06-04 12:14:25 +0200] [8921] [INFO] Booting worker with pid: 8921
[2018-06-04 12:21:31 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8921)
[2018-06-04 12:21:32 +0200] [8929] [INFO] Booting worker with pid: 8929
[2018-06-04 12:22:20 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8929)
[2018-06-04 12:22:21 +0200] [8932] [INFO] Booting worker with pid: 8932
[2018-06-04 12:24:54 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8932)
[2018-06-04 12:24:54 +0200] [8932] [INFO] Worker exiting (pid: 8932)
[2018-06-04 12:24:54 +0200] [8935] [INFO] Booting worker with pid: 8935
[2018-06-04 12:26:40 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8935)
[2018-06-04 12:26:41 +0200] [8939] [INFO] Booting worker with pid: 8939
[2018-06-04 12:27:48 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8939)
[2018-06-04 12:27:49 +0200] [8950] [INFO] Booting worker with pid: 8950
[2018-06-04 12:40:33 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:8950)
[2018-06-04 12:40:34 +0200] [10281] [INFO] Booting worker with pid: 10281
[2018-06-04 12:43:06 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:10281)
[2018-06-04 12:43:07 +0200] [10316] [INFO] Booting worker with pid: 10316
[2018-06-04 12:52:15 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:10316)
[2018-06-04 12:52:16 +0200] [10961] [INFO] Booting worker with pid: 10961
[2018-06-04 12:59:24 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:10961)
[2018-06-04 12:59:25 +0200] [11035] [INFO] Booting worker with pid: 11035
[2018-06-04 13:00:09 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:11035)
[2018-06-04 13:00:10 +0200] [11038] [INFO] Booting worker with pid: 11038
[2018-06-04 13:00:49 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:11038)
[2018-06-04 13:00:50 +0200] [11041] [INFO] Booting worker with pid: 11041
[2018-06-04 13:02:38 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:11041)
[2018-06-04 13:02:39 +0200] [11044] [INFO] Booting worker with pid: 11044
[2018-06-04 13:04:30 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:11044)
[2018-06-04 13:04:30 +0200] [11044] [INFO] Worker exiting (pid: 11044)
[2018-06-04 13:04:30 +0200] [11047] [INFO] Booting worker with pid: 11047
[2018-06-04 13:06:50 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:11047)
[2018-06-04 13:06:51 +0200] [11051] [INFO] Booting worker with pid: 11051
[2018-06-04 15:19:23 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:11051)
[2018-06-04 15:19:24 +0200] [11141] [INFO] Booting worker with pid: 11141
[2018-06-04 15:22:43 +0200] [5580] [CRITICAL] WORKER TIMEOUT (pid:11141)
[2018-06-04 15:22:43 +0200] [11141] [INFO] Worker exiting (pid: 11141)
[2018-06-04 15:22:44 +0200] [11145] [INFO] Booting worker with pid: 11145
[2018-06-05 08:53:09 +0200] [11145] [INFO] Worker exiting (pid: 11145)
[2018-06-05 08:53:09 +0200] [5580] [INFO] Handling signal: term
[2018-06-05 08:53:09 +0200] [5580] [INFO] Shutting down: Master
[2018-06-05 08:53:10 +0200] [11837] [INFO] Starting gunicorn 19.8.1
[2018-06-05 08:53:10 +0200] [11837] [INFO] Listening at: http://0.0.0.0:7777 (11837)
[2018-06-05 08:53:10 +0200] [11837] [INFO] Using worker: sync
[2018-06-05 08:53:10 +0200] [11843] [INFO] Booting worker with pid: 11843
[2018-06-05 09:16:23 +0200] [11837] [INFO] Handling signal: term
[2018-06-05 09:16:23 +0200] [11843] [INFO] Worker exiting (pid: 11843)
[2018-06-05 09:16:24 +0200] [11837] [INFO] Shutting down: Master
[2018-06-05 09:16:24 +0200] [11990] [INFO] Starting gunicorn 19.8.1
[2018-06-05 09:16:24 +0200] [11990] [INFO] Listening at: http://0.0.0.0:7777 (11990)
[2018-06-05 09:16:24 +0200] [11990] [INFO] Using worker: sync
[2018-06-05 09:16:24 +0200] [11996] [INFO] Booting worker with pid: 11996
[2018-06-05 09:38:12 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:11996)
[2018-06-05 09:38:13 +0200] [12010] [INFO] Booting worker with pid: 12010
[2018-06-05 09:40:08 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12010)
[2018-06-05 09:40:09 +0200] [12013] [INFO] Booting worker with pid: 12013
[2018-06-05 09:43:22 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12013)
[2018-06-05 09:43:23 +0200] [12016] [INFO] Booting worker with pid: 12016
[2018-06-05 09:48:09 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12016)
[2018-06-05 09:48:10 +0200] [12020] [INFO] Booting worker with pid: 12020
[2018-06-05 09:55:43 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12020)
[2018-06-05 09:55:44 +0200] [12024] [INFO] Booting worker with pid: 12024
[2018-06-05 10:00:33 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12024)
[2018-06-05 10:00:34 +0200] [12179] [INFO] Booting worker with pid: 12179
[2018-06-05 10:03:40 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12179)
[2018-06-05 10:03:41 +0200] [12300] [INFO] Booting worker with pid: 12300
[2018-06-05 10:07:12 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12300)
[2018-06-05 10:07:13 +0200] [12424] [INFO] Booting worker with pid: 12424
[2018-06-05 10:17:07 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12424)
[2018-06-05 10:17:08 +0200] [12549] [INFO] Booting worker with pid: 12549
[2018-06-05 10:17:57 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12549)
[2018-06-05 10:17:59 +0200] [12552] [INFO] Booting worker with pid: 12552
[2018-06-05 10:21:17 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12552)
[2018-06-05 10:21:18 +0200] [12670] [INFO] Booting worker with pid: 12670
[2018-06-05 10:23:02 +0200] [11990] [CRITICAL] WORKER TIMEOUT (pid:12670)
[2018-06-05 10:23:03 +0200] [12789] [INFO] Booting worker with pid: 12789
[2018-06-05 10:35:49 +0200] [12789] [INFO] Worker exiting (pid: 12789)
[2018-06-05 10:35:49 +0200] [11990] [INFO] Handling signal: term
[2018-06-05 10:35:49 +0200] [11990] [INFO] Shutting down: Master
[2018-06-05 10:35:49 +0200] [12827] [INFO] Starting gunicorn 19.8.1
[2018-06-05 10:35:49 +0200] [12827] [INFO] Listening at: http://0.0.0.0:7777 (12827)
[2018-06-05 10:35:49 +0200] [12827] [INFO] Using worker: sync
[2018-06-05 10:35:49 +0200] [12833] [INFO] Booting worker with pid: 12833
[2018-06-05 10:36:07 +0200] [12827] [INFO] Handling signal: term
[2018-06-05 10:36:07 +0200] [12833] [INFO] Worker exiting (pid: 12833)
[2018-06-05 10:36:07 +0200] [12827] [INFO] Shutting down: Master
[2018-06-05 10:36:07 +0200] [12858] [INFO] Starting gunicorn 19.8.1
[2018-06-05 10:36:07 +0200] [12858] [INFO] Listening at: http://0.0.0.0:7777 (12858)
[2018-06-05 10:36:07 +0200] [12858] [INFO] Using worker: sync
[2018-06-05 10:36:07 +0200] [12865] [INFO] Booting worker with pid: 12865
[2018-06-05 11:16:08 +0200] [12865] [INFO] Worker exiting (pid: 12865)
[2018-06-05 11:16:08 +0200] [12858] [INFO] Handling signal: term
[2018-06-05 11:16:08 +0200] [12858] [INFO] Shutting down: Master
[2018-06-05 11:16:08 +0200] [12989] [INFO] Starting gunicorn 19.8.1
[2018-06-05 11:16:08 +0200] [12989] [INFO] Listening at: http://0.0.0.0:7777 (12989)
[2018-06-05 11:16:08 +0200] [12989] [INFO] Using worker: sync
[2018-06-05 11:16:08 +0200] [12995] [INFO] Booting worker with pid: 12995
[2018-06-06 10:35:06 +0200] [12989] [INFO] Handling signal: term
[2018-06-06 10:35:06 +0200] [12995] [INFO] Worker exiting (pid: 12995)
[2018-06-06 10:35:06 +0200] [12989] [INFO] Shutting down: Master
[2018-06-06 10:35:06 +0200] [17076] [INFO] Starting gunicorn 19.8.1
[2018-06-06 10:35:06 +0200] [17076] [INFO] Listening at: http://0.0.0.0:7777 (17076)
[2018-06-06 10:35:06 +0200] [17076] [INFO] Using worker: sync
[2018-06-06 10:35:06 +0200] [17082] [INFO] Booting worker with pid: 17082
[2018-06-06 10:35:07 +0200] [17082] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 139, in <module>
    @app.route("/a", methods=["POST", "GET"])
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: formulario
[2018-06-06 10:35:07 +0200] [17082] [INFO] Worker exiting (pid: 17082)
[2018-06-06 10:35:07 +0200] [17076] [INFO] Shutting down: Master
[2018-06-06 10:35:07 +0200] [17076] [INFO] Reason: Worker failed to boot.
[2018-06-06 10:35:07 +0200] [17087] [INFO] Starting gunicorn 19.8.1
[2018-06-06 10:35:07 +0200] [17087] [INFO] Listening at: http://0.0.0.0:7777 (17087)
[2018-06-06 10:35:07 +0200] [17087] [INFO] Using worker: sync
[2018-06-06 10:35:07 +0200] [17091] [INFO] Booting worker with pid: 17091
[2018-06-06 10:35:08 +0200] [17091] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 139, in <module>
    @app.route("/a", methods=["POST", "GET"])
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: formulario
[2018-06-06 10:35:08 +0200] [17091] [INFO] Worker exiting (pid: 17091)
[2018-06-06 10:35:08 +0200] [17087] [INFO] Shutting down: Master
[2018-06-06 10:35:08 +0200] [17087] [INFO] Reason: Worker failed to boot.
[2018-06-06 10:35:08 +0200] [17095] [INFO] Starting gunicorn 19.8.1
[2018-06-06 10:35:08 +0200] [17095] [INFO] Listening at: http://0.0.0.0:7777 (17095)
[2018-06-06 10:35:08 +0200] [17095] [INFO] Using worker: sync
[2018-06-06 10:35:08 +0200] [17099] [INFO] Booting worker with pid: 17099
[2018-06-06 10:35:08 +0200] [17099] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 139, in <module>
    @app.route("/a", methods=["POST", "GET"])
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: formulario
[2018-06-06 10:35:08 +0200] [17099] [INFO] Worker exiting (pid: 17099)
[2018-06-06 10:35:08 +0200] [17095] [INFO] Shutting down: Master
[2018-06-06 10:35:08 +0200] [17095] [INFO] Reason: Worker failed to boot.
[2018-06-06 10:35:09 +0200] [17103] [INFO] Starting gunicorn 19.8.1
[2018-06-06 10:35:09 +0200] [17103] [INFO] Listening at: http://0.0.0.0:7777 (17103)
[2018-06-06 10:35:09 +0200] [17103] [INFO] Using worker: sync
[2018-06-06 10:35:09 +0200] [17107] [INFO] Booting worker with pid: 17107
[2018-06-06 10:35:09 +0200] [17107] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 139, in <module>
    @app.route("/a", methods=["POST", "GET"])
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: formulario
[2018-06-06 10:35:09 +0200] [17107] [INFO] Worker exiting (pid: 17107)
[2018-06-06 10:35:09 +0200] [17103] [INFO] Shutting down: Master
[2018-06-06 10:35:09 +0200] [17103] [INFO] Reason: Worker failed to boot.
[2018-06-06 10:35:10 +0200] [17111] [INFO] Starting gunicorn 19.8.1
[2018-06-06 10:35:10 +0200] [17111] [INFO] Listening at: http://0.0.0.0:7777 (17111)
[2018-06-06 10:35:10 +0200] [17111] [INFO] Using worker: sync
[2018-06-06 10:35:10 +0200] [17115] [INFO] Booting worker with pid: 17115
[2018-06-06 10:35:10 +0200] [17115] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/listas/consulta_fondo/app.py", line 139, in <module>
    @app.route("/a", methods=["POST", "GET"])
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: formulario
[2018-06-06 10:35:10 +0200] [17115] [INFO] Worker exiting (pid: 17115)
[2018-06-06 10:35:10 +0200] [17111] [INFO] Shutting down: Master
[2018-06-06 10:35:10 +0200] [17111] [INFO] Reason: Worker failed to boot.
[2018-06-06 10:38:07 +0200] [17338] [INFO] Starting gunicorn 19.8.1
[2018-06-06 10:38:07 +0200] [17338] [INFO] Listening at: http://0.0.0.0:7777 (17338)
[2018-06-06 10:38:07 +0200] [17338] [INFO] Using worker: sync
[2018-06-06 10:38:07 +0200] [17343] [INFO] Booting worker with pid: 17343
[2018-06-06 10:38:25,651] ERROR in app: Exception on /a [GET]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 141, in formularioa
    fondo = pd.read_csv('g8dqb.csv', sep=';')
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'g8dqb.csv' does not exist
[2018-06-06 10:46:10 +0200] [17338] [INFO] Handling signal: term
[2018-06-06 10:46:10 +0200] [17343] [INFO] Worker exiting (pid: 17343)
[2018-06-06 10:46:10 +0200] [17338] [INFO] Shutting down: Master
[2018-06-06 10:46:10 +0200] [17366] [INFO] Starting gunicorn 19.8.1
[2018-06-06 10:46:10 +0200] [17366] [INFO] Listening at: http://0.0.0.0:7777 (17366)
[2018-06-06 10:46:10 +0200] [17366] [INFO] Using worker: sync
[2018-06-06 10:46:10 +0200] [17371] [INFO] Booting worker with pid: 17371
[2018-06-06 10:46:15,251] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 141, in formularioa
    fondo = pd.read_csv('g8dqb.csv', sep=';')
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'g8dqb.csv' does not exist
[2018-06-06 10:46:23,512] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 141, in formularioa
    fondo = pd.read_csv('g8dqb.csv', sep=';')
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'g8dqb.csv' does not exist
[2018-06-06 10:46:32 +0200] [17366] [INFO] Handling signal: term
[2018-06-06 10:46:32 +0200] [17371] [INFO] Worker exiting (pid: 17371)
[2018-06-06 10:46:32 +0200] [17366] [INFO] Shutting down: Master
[2018-06-06 11:03:47 +0200] [17796] [INFO] Starting gunicorn 19.8.1
[2018-06-06 11:03:47 +0200] [17796] [INFO] Listening at: http://0.0.0.0:7777 (17796)
[2018-06-06 11:03:47 +0200] [17796] [INFO] Using worker: sync
[2018-06-06 11:03:47 +0200] [17802] [INFO] Booting worker with pid: 17802
[2018-06-06 11:34:24 +0200] [17796] [INFO] Handling signal: term
[2018-06-06 11:34:24 +0200] [17802] [INFO] Worker exiting (pid: 17802)
[2018-06-06 11:34:24 +0200] [17796] [INFO] Shutting down: Master
[2018-06-06 11:34:24 +0200] [17841] [INFO] Starting gunicorn 19.8.1
[2018-06-06 11:34:24 +0200] [17841] [INFO] Listening at: http://0.0.0.0:7777 (17841)
[2018-06-06 11:34:24 +0200] [17841] [INFO] Using worker: sync
[2018-06-06 11:34:24 +0200] [17847] [INFO] Booting worker with pid: 17847
[2018-06-06 12:46:49 +0200] [17847] [INFO] Worker exiting (pid: 17847)
[2018-06-06 12:46:49 +0200] [17841] [INFO] Handling signal: term
[2018-06-06 12:46:50 +0200] [17841] [INFO] Shutting down: Master
[2018-06-06 13:27:54 +0200] [18347] [INFO] Starting gunicorn 19.8.1
[2018-06-06 13:27:54 +0200] [18347] [INFO] Listening at: http://0.0.0.0:7777 (18347)
[2018-06-06 13:27:54 +0200] [18347] [INFO] Using worker: sync
[2018-06-06 13:27:54 +0200] [18353] [INFO] Booting worker with pid: 18353
[2018-06-06 13:33:20 +0200] [18347] [INFO] Handling signal: term
[2018-06-06 13:33:20 +0200] [18353] [INFO] Worker exiting (pid: 18353)
[2018-06-06 13:33:20 +0200] [18347] [INFO] Shutting down: Master
[2018-06-06 13:33:20 +0200] [18397] [INFO] Starting gunicorn 19.8.1
[2018-06-06 13:33:20 +0200] [18397] [INFO] Listening at: http://0.0.0.0:7777 (18397)
[2018-06-06 13:33:20 +0200] [18397] [INFO] Using worker: sync
[2018-06-06 13:33:20 +0200] [18403] [INFO] Booting worker with pid: 18403
[2018-06-06 13:33:40 +0200] [18397] [INFO] Handling signal: term
[2018-06-06 13:33:40 +0200] [18403] [INFO] Worker exiting (pid: 18403)
[2018-06-06 13:33:40 +0200] [18397] [INFO] Shutting down: Master
[2018-06-06 14:14:16 +0200] [18507] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:14:16 +0200] [18507] [INFO] Listening at: http://0.0.0.0:7777 (18507)
[2018-06-06 14:14:16 +0200] [18507] [INFO] Using worker: sync
[2018-06-06 14:14:16 +0200] [18511] [INFO] Booting worker with pid: 18511
[2018-06-06 14:25:47 +0200] [18507] [INFO] Handling signal: term
[2018-06-06 14:25:47 +0200] [18511] [INFO] Worker exiting (pid: 18511)
[2018-06-06 14:25:47 +0200] [18507] [INFO] Shutting down: Master
[2018-06-06 14:26:51 +0200] [18658] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:26:51 +0200] [18658] [INFO] Listening at: http://0.0.0.0:7777 (18658)
[2018-06-06 14:26:51 +0200] [18658] [INFO] Using worker: sync
[2018-06-06 14:26:51 +0200] [18662] [INFO] Booting worker with pid: 18662
[2018-06-06 14:27:27 +0200] [18662] [INFO] Worker exiting (pid: 18662)
[2018-06-06 14:27:27 +0200] [18658] [INFO] Handling signal: term
[2018-06-06 14:27:27 +0200] [18658] [INFO] Shutting down: Master
[2018-06-06 14:27:31 +0200] [18736] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:27:31 +0200] [18736] [INFO] Listening at: http://0.0.0.0:7777 (18736)
[2018-06-06 14:27:31 +0200] [18736] [INFO] Using worker: sync
[2018-06-06 14:27:31 +0200] [18740] [INFO] Booting worker with pid: 18740
[2018-06-06 14:27:48 +0200] [18736] [INFO] Handling signal: term
[2018-06-06 14:27:48 +0200] [18740] [INFO] Worker exiting (pid: 18740)
[2018-06-06 14:27:48 +0200] [18736] [INFO] Shutting down: Master
[2018-06-06 14:27:48 +0200] [18760] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:27:48 +0200] [18760] [INFO] Listening at: http://0.0.0.0:7777 (18760)
[2018-06-06 14:27:48 +0200] [18760] [INFO] Using worker: sync
[2018-06-06 14:27:48 +0200] [18765] [INFO] Booting worker with pid: 18765
[2018-06-06 14:29:06 +0200] [18760] [INFO] Handling signal: term
[2018-06-06 14:29:06 +0200] [18765] [INFO] Worker exiting (pid: 18765)
[2018-06-06 14:29:06 +0200] [18760] [INFO] Shutting down: Master
[2018-06-06 14:29:06 +0200] [18785] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:29:06 +0200] [18785] [INFO] Listening at: http://0.0.0.0:7777 (18785)
[2018-06-06 14:29:06 +0200] [18785] [INFO] Using worker: sync
[2018-06-06 14:29:06 +0200] [18790] [INFO] Booting worker with pid: 18790
[2018-06-06 14:33:50 +0200] [18785] [INFO] Handling signal: term
[2018-06-06 14:33:50 +0200] [18790] [INFO] Worker exiting (pid: 18790)
[2018-06-06 14:33:50 +0200] [18785] [INFO] Shutting down: Master
[2018-06-06 14:33:50 +0200] [18815] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:33:50 +0200] [18815] [INFO] Listening at: http://0.0.0.0:7777 (18815)
[2018-06-06 14:33:50 +0200] [18815] [INFO] Using worker: sync
[2018-06-06 14:33:50 +0200] [18821] [INFO] Booting worker with pid: 18821
[2018-06-06 14:41:00 +0200] [18815] [INFO] Handling signal: term
[2018-06-06 14:41:00 +0200] [18821] [INFO] Worker exiting (pid: 18821)
[2018-06-06 14:41:00 +0200] [18815] [INFO] Shutting down: Master
[2018-06-06 14:41:01 +0200] [19019] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:41:01 +0200] [19019] [INFO] Listening at: http://0.0.0.0:7777 (19019)
[2018-06-06 14:41:01 +0200] [19019] [INFO] Using worker: sync
[2018-06-06 14:41:01 +0200] [19024] [INFO] Booting worker with pid: 19024
[2018-06-06 14:41:30 +0200] [19019] [INFO] Handling signal: term
[2018-06-06 14:42:00 +0200] [19019] [INFO] Shutting down: Master
[2018-06-06 14:42:00 +0200] [19063] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:42:00 +0200] [19063] [INFO] Listening at: http://0.0.0.0:7777 (19063)
[2018-06-06 14:42:00 +0200] [19063] [INFO] Using worker: sync
[2018-06-06 14:42:00 +0200] [19069] [INFO] Booting worker with pid: 19069
[2018-06-06 14:44:43 +0200] [19069] [INFO] Worker exiting (pid: 19069)
[2018-06-06 14:44:43 +0200] [19063] [INFO] Handling signal: term
[2018-06-06 14:44:43 +0200] [19063] [INFO] Shutting down: Master
[2018-06-06 14:44:43 +0200] [19105] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:44:43 +0200] [19105] [INFO] Listening at: http://0.0.0.0:7777 (19105)
[2018-06-06 14:44:43 +0200] [19105] [INFO] Using worker: sync
[2018-06-06 14:44:43 +0200] [19111] [INFO] Booting worker with pid: 19111
[2018-06-06 14:44:53 +0200] [19105] [INFO] Handling signal: term
[2018-06-06 14:44:53 +0200] [19111] [INFO] Worker exiting (pid: 19111)
[2018-06-06 14:44:53 +0200] [19105] [INFO] Shutting down: Master
[2018-06-06 14:44:53 +0200] [19136] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:44:53 +0200] [19136] [INFO] Listening at: http://0.0.0.0:7777 (19136)
[2018-06-06 14:44:53 +0200] [19136] [INFO] Using worker: sync
[2018-06-06 14:44:53 +0200] [19140] [INFO] Booting worker with pid: 19140
[2018-06-06 14:46:09 +0200] [19136] [INFO] Handling signal: term
[2018-06-06 14:46:09 +0200] [19140] [INFO] Worker exiting (pid: 19140)
[2018-06-06 14:46:09 +0200] [19136] [INFO] Shutting down: Master
[2018-06-06 14:46:09 +0200] [19178] [INFO] Starting gunicorn 19.8.1
[2018-06-06 14:46:09 +0200] [19178] [INFO] Listening at: http://0.0.0.0:7777 (19178)
[2018-06-06 14:46:09 +0200] [19178] [INFO] Using worker: sync
[2018-06-06 14:46:09 +0200] [19182] [INFO] Booting worker with pid: 19182
[2018-06-06 15:47:22 +0200] [19182] [INFO] Worker exiting (pid: 19182)
[2018-06-06 15:47:22 +0200] [19178] [INFO] Handling signal: term
[2018-06-06 15:47:23 +0200] [19178] [INFO] Shutting down: Master
[2018-06-06 15:47:23 +0200] [19332] [INFO] Starting gunicorn 19.8.1
[2018-06-06 15:47:23 +0200] [19332] [INFO] Listening at: http://0.0.0.0:7777 (19332)
[2018-06-06 15:47:23 +0200] [19332] [INFO] Using worker: sync
[2018-06-06 15:47:23 +0200] [19338] [INFO] Booting worker with pid: 19338
[2018-06-06 15:50:16 +0200] [19332] [INFO] Handling signal: term
[2018-06-06 15:50:16 +0200] [19338] [INFO] Worker exiting (pid: 19338)
[2018-06-06 15:50:16 +0200] [19332] [INFO] Shutting down: Master
[2018-06-06 15:50:16 +0200] [19358] [INFO] Starting gunicorn 19.8.1
[2018-06-06 15:50:16 +0200] [19358] [INFO] Listening at: http://0.0.0.0:7777 (19358)
[2018-06-06 15:50:16 +0200] [19358] [INFO] Using worker: sync
[2018-06-06 15:50:16 +0200] [19364] [INFO] Booting worker with pid: 19364
[2018-06-06 15:57:11 +0200] [19358] [INFO] Handling signal: term
[2018-06-06 15:57:11 +0200] [19364] [INFO] Worker exiting (pid: 19364)
[2018-06-06 15:57:12 +0200] [19358] [INFO] Shutting down: Master
[2018-06-06 15:57:12 +0200] [19385] [INFO] Starting gunicorn 19.8.1
[2018-06-06 15:57:12 +0200] [19385] [INFO] Listening at: http://0.0.0.0:7777 (19385)
[2018-06-06 15:57:12 +0200] [19385] [INFO] Using worker: sync
[2018-06-06 15:57:12 +0200] [19391] [INFO] Booting worker with pid: 19391
[2018-06-06 15:59:13 +0200] [19391] [INFO] Worker exiting (pid: 19391)
[2018-06-06 15:59:13 +0200] [19385] [INFO] Handling signal: term
[2018-06-06 15:59:13 +0200] [19385] [INFO] Shutting down: Master
[2018-06-06 15:59:13 +0200] [19414] [INFO] Starting gunicorn 19.8.1
[2018-06-06 15:59:13 +0200] [19414] [INFO] Listening at: http://0.0.0.0:7777 (19414)
[2018-06-06 15:59:13 +0200] [19414] [INFO] Using worker: sync
[2018-06-06 15:59:13 +0200] [19420] [INFO] Booting worker with pid: 19420
[2018-06-06 16:18:09 +0200] [19420] [INFO] Worker exiting (pid: 19420)
[2018-06-06 16:18:09 +0200] [19414] [INFO] Handling signal: term
[2018-06-06 16:18:09 +0200] [19414] [INFO] Shutting down: Master
[2018-06-06 16:18:09 +0200] [19450] [INFO] Starting gunicorn 19.8.1
[2018-06-06 16:18:09 +0200] [19450] [INFO] Listening at: http://0.0.0.0:7777 (19450)
[2018-06-06 16:18:09 +0200] [19450] [INFO] Using worker: sync
[2018-06-06 16:18:09 +0200] [19455] [INFO] Booting worker with pid: 19455
[2018-06-06 16:19:15 +0200] [19455] [INFO] Worker exiting (pid: 19455)
[2018-06-06 16:19:15 +0200] [19450] [INFO] Handling signal: term
[2018-06-06 16:19:15 +0200] [19450] [INFO] Shutting down: Master
[2018-06-06 16:19:15 +0200] [19474] [INFO] Starting gunicorn 19.8.1
[2018-06-06 16:19:15 +0200] [19474] [INFO] Listening at: http://0.0.0.0:7777 (19474)
[2018-06-06 16:19:15 +0200] [19474] [INFO] Using worker: sync
[2018-06-06 16:19:15 +0200] [19480] [INFO] Booting worker with pid: 19480
[2018-06-07 10:00:24 +0200] [19480] [INFO] Worker exiting (pid: 19480)
[2018-06-07 10:00:24 +0200] [19474] [INFO] Handling signal: term
[2018-06-07 10:00:24 +0200] [19474] [INFO] Shutting down: Master
[2018-06-07 10:00:25 +0200] [20498] [INFO] Starting gunicorn 19.8.1
[2018-06-07 10:00:25 +0200] [20498] [INFO] Listening at: http://0.0.0.0:7777 (20498)
[2018-06-07 10:00:25 +0200] [20498] [INFO] Using worker: sync
[2018-06-07 10:00:25 +0200] [20504] [INFO] Booting worker with pid: 20504
[2018-06-07 10:00:57,210] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 163, in formulario
    listaIsbnEncontrados = fondo_filtrado.loc[:, 'ISBN'].tolist()
AttributeError: 'Styler' object has no attribute 'loc'
[2018-06-07 10:01:04 +0200] [20504] [INFO] Worker exiting (pid: 20504)
[2018-06-07 10:01:04 +0200] [20498] [INFO] Handling signal: term
[2018-06-07 10:01:04 +0200] [20498] [INFO] Shutting down: Master
[2018-06-07 11:25:52 +0200] [21296] [INFO] Starting gunicorn 19.8.1
[2018-06-07 11:25:52 +0200] [21296] [INFO] Listening at: http://0.0.0.0:7777 (21296)
[2018-06-07 11:25:52 +0200] [21296] [INFO] Using worker: sync
[2018-06-07 11:25:52 +0200] [21300] [INFO] Booting worker with pid: 21300
[2018-06-07 11:59:04 +0200] [21296] [INFO] Handling signal: term
[2018-06-07 11:59:04 +0200] [21300] [INFO] Worker exiting (pid: 21300)
[2018-06-07 11:59:04 +0200] [21296] [INFO] Shutting down: Master
[2018-06-07 11:59:04 +0200] [21330] [INFO] Starting gunicorn 19.8.1
[2018-06-07 11:59:04 +0200] [21330] [INFO] Listening at: http://0.0.0.0:7777 (21330)
[2018-06-07 11:59:04 +0200] [21330] [INFO] Using worker: sync
[2018-06-07 11:59:04 +0200] [21335] [INFO] Booting worker with pid: 21335
[2018-06-07 12:19:14 +0200] [21335] [INFO] Worker exiting (pid: 21335)
[2018-06-07 12:19:14 +0200] [21330] [INFO] Handling signal: term
[2018-06-07 12:19:14 +0200] [21330] [INFO] Shutting down: Master
[2018-06-07 12:19:14 +0200] [21361] [INFO] Starting gunicorn 19.8.1
[2018-06-07 12:19:14 +0200] [21361] [INFO] Listening at: http://0.0.0.0:7777 (21361)
[2018-06-07 12:19:14 +0200] [21361] [INFO] Using worker: sync
[2018-06-07 12:19:14 +0200] [21367] [INFO] Booting worker with pid: 21367
[2018-06-07 16:24:06 +0200] [21361] [INFO] Handling signal: term
[2018-06-07 16:24:06 +0200] [21367] [INFO] Worker exiting (pid: 21367)
[2018-06-07 16:24:07 +0200] [21361] [INFO] Shutting down: Master
[2018-06-07 16:24:07 +0200] [21509] [INFO] Starting gunicorn 19.8.1
[2018-06-07 16:24:07 +0200] [21509] [INFO] Listening at: http://0.0.0.0:7777 (21509)
[2018-06-07 16:24:07 +0200] [21509] [INFO] Using worker: sync
[2018-06-07 16:24:07 +0200] [21515] [INFO] Booting worker with pid: 21515
[2018-06-07 16:37:30 +0200] [21515] [INFO] Worker exiting (pid: 21515)
[2018-06-07 16:37:30 +0200] [21509] [INFO] Handling signal: term
[2018-06-07 16:37:30 +0200] [21509] [INFO] Shutting down: Master
[2018-06-07 16:37:30 +0200] [21553] [INFO] Starting gunicorn 19.8.1
[2018-06-07 16:37:30 +0200] [21553] [INFO] Listening at: http://0.0.0.0:7777 (21553)
[2018-06-07 16:37:30 +0200] [21553] [INFO] Using worker: sync
[2018-06-07 16:37:30 +0200] [21558] [INFO] Booting worker with pid: 21558
[2018-06-07 16:43:20 +0200] [21558] [INFO] Worker exiting (pid: 21558)
[2018-06-07 16:43:20 +0200] [21553] [INFO] Handling signal: term
[2018-06-07 16:43:20 +0200] [21553] [INFO] Shutting down: Master
[2018-06-07 16:43:20 +0200] [21584] [INFO] Starting gunicorn 19.8.1
[2018-06-07 16:43:20 +0200] [21584] [INFO] Listening at: http://0.0.0.0:7777 (21584)
[2018-06-07 16:43:20 +0200] [21584] [INFO] Using worker: sync
[2018-06-07 16:43:20 +0200] [21590] [INFO] Booting worker with pid: 21590
[2018-06-08 10:28:23 +0200] [21584] [INFO] Handling signal: term
[2018-06-08 10:28:53 +0200] [21584] [INFO] Shutting down: Master
[2018-06-08 10:28:53 +0200] [22496] [INFO] Starting gunicorn 19.8.1
[2018-06-08 10:28:53 +0200] [22496] [INFO] Listening at: http://0.0.0.0:7777 (22496)
[2018-06-08 10:28:53 +0200] [22496] [INFO] Using worker: sync
[2018-06-08 10:28:53 +0200] [22502] [INFO] Booting worker with pid: 22502
[2018-06-08 10:29:32 +0200] [22496] [INFO] Handling signal: term
[2018-06-08 10:29:32 +0200] [22502] [INFO] Worker exiting (pid: 22502)
[2018-06-08 10:29:33 +0200] [22496] [INFO] Shutting down: Master
[2018-06-08 10:29:55 +0200] [1212] [INFO] Starting gunicorn 19.8.1
[2018-06-08 10:29:55 +0200] [1212] [INFO] Listening at: http://0.0.0.0:7777 (1212)
[2018-06-08 10:29:55 +0200] [1212] [INFO] Using worker: sync
[2018-06-08 10:29:55 +0200] [1433] [INFO] Booting worker with pid: 1433
[2018-06-08 10:34:35 +0200] [1433] [INFO] Worker exiting (pid: 1433)
[2018-06-08 10:34:35 +0200] [1212] [INFO] Handling signal: term
[2018-06-08 10:34:35 +0200] [1212] [INFO] Shutting down: Master
[2018-06-08 10:34:35 +0200] [1783] [INFO] Starting gunicorn 19.8.1
[2018-06-08 10:34:35 +0200] [1783] [INFO] Listening at: http://0.0.0.0:7777 (1783)
[2018-06-08 10:34:35 +0200] [1783] [INFO] Using worker: sync
[2018-06-08 10:34:35 +0200] [1787] [INFO] Booting worker with pid: 1787
[2018-06-08 10:34:58 +0200] [1783] [INFO] Handling signal: term
[2018-06-08 10:34:58 +0200] [1787] [INFO] Worker exiting (pid: 1787)
[2018-06-08 10:34:58 +0200] [1783] [INFO] Shutting down: Master
[2018-06-08 10:34:58 +0200] [1802] [INFO] Starting gunicorn 19.8.1
[2018-06-08 10:34:58 +0200] [1802] [INFO] Listening at: http://0.0.0.0:7777 (1802)
[2018-06-08 10:34:58 +0200] [1802] [INFO] Using worker: sync
[2018-06-08 10:34:58 +0200] [1807] [INFO] Booting worker with pid: 1807
[2018-06-08 11:16:29 +0200] [1802] [INFO] Handling signal: term
[2018-06-08 11:16:29 +0200] [1807] [INFO] Worker exiting (pid: 1807)
[2018-06-08 11:16:29 +0200] [1802] [INFO] Shutting down: Master
[2018-06-08 11:16:29 +0200] [1863] [INFO] Starting gunicorn 19.8.1
[2018-06-08 11:16:29 +0200] [1863] [INFO] Listening at: http://0.0.0.0:7777 (1863)
[2018-06-08 11:16:29 +0200] [1863] [INFO] Using worker: sync
[2018-06-08 11:16:29 +0200] [1868] [INFO] Booting worker with pid: 1868
[2018-06-08 11:16:43,061] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/listas/consulta_fondo/listasvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/listas/consulta_fondo/app.py", line 128, in formulario
    listaIsbnConsulta[i] = re.sub("[^0-9]", "", item)
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
[2018-06-08 11:16:50 +0200] [1863] [INFO] Handling signal: term
[2018-06-08 11:16:50 +0200] [1868] [INFO] Worker exiting (pid: 1868)
[2018-06-08 11:16:50 +0200] [1863] [INFO] Shutting down: Master
[2018-06-08 11:20:21 +0200] [1982] [INFO] Starting gunicorn 19.8.1
[2018-06-08 11:20:21 +0200] [1982] [INFO] Listening at: http://0.0.0.0:7777 (1982)
[2018-06-08 11:20:21 +0200] [1982] [INFO] Using worker: sync
[2018-06-08 11:20:21 +0200] [1987] [INFO] Booting worker with pid: 1987
[2018-06-08 12:00:04 +0200] [1987] [INFO] Worker exiting (pid: 1987)
[2018-06-08 12:00:04 +0200] [1982] [INFO] Handling signal: term
[2018-06-08 12:00:05 +0200] [1982] [INFO] Shutting down: Master
[2018-06-08 12:05:03 +0200] [2167] [INFO] Starting gunicorn 19.8.1
[2018-06-08 12:05:03 +0200] [2167] [INFO] Listening at: http://0.0.0.0:7777 (2167)
[2018-06-08 12:05:03 +0200] [2167] [INFO] Using worker: sync
[2018-06-08 12:05:03 +0200] [2173] [INFO] Booting worker with pid: 2173
[2018-06-11 09:19:25 +0200] [2167] [INFO] Handling signal: term
[2018-06-11 09:19:55 +0200] [2167] [INFO] Shutting down: Master
[2018-06-11 09:19:55 +0200] [4925] [INFO] Starting gunicorn 19.8.1
[2018-06-11 09:19:55 +0200] [4925] [INFO] Listening at: http://0.0.0.0:7777 (4925)
[2018-06-11 09:19:55 +0200] [4925] [INFO] Using worker: sync
[2018-06-11 09:19:55 +0200] [4931] [INFO] Booting worker with pid: 4931
